version: "3.5"
services:

  runner.nginx:
    build:
      context: ./runner.nginx/
    image: runner.nginx:dev
    container_name: runner.nginx
    env_file:
      - .env
    environment:
      UID_VAR: {{ UID_VALUE }}
      GID_VAR: {{ GID_VALUE }}
    ports:
      - "${HOST_NGINX_PORT}:80"
    links:
        - runner.php
    volumes:
      - {{ VOLUME_WEB }}
    networks:
      - dev_network

  runner.php:
    build: runner.php
    image: runner.php:dev
    container_name: runner.php
    env_file:
      - .env
    environment:
      XDEBUG_CONFIG: remote_host=${HOST_IP}
      PHP_IDE_CONFIG: serverName=${PHPSTORM_SERVER_NAME}
      UID_VAR: {{ UID_VALUE }}
      GID_VAR: {{ GID_VALUE }}
      UID: {{ UID_VALUE }}
      GID: {{ GID_VALUE }}
    expose:
      - "9000"
    networks:
      - dev_network
    volumes:
      - {{ VOLUME }}
    links:
      - runner.db
      - runner.memcached
      - runner.mq

  runner.db:
    build:
      context: ./runner.db/
    image: runner.db:dev
    container_name: runner.db
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${COMMAND_DATABASE_NAME}
      MYSQL_USER: ${COMMAND_DATABASE_USER}
      MYSQL_ROOT_PASSWORD: ${COMMAND_DATABASE_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${COMMAND_DATABASE_PASSWORD}
    ports:
      - "${HOST_DATABASE_PORT}:${COMMAND_DATABASE_PORT}"
    networks:
      - dev_network

  runner.memcached:
    image: memcached:alpine
    container_name: runner-memcached
    networks:
      - dev_network

  runner.mq:
    build: runner.mq
    image: runner.mq:dev
    container_name: runner.mq
    env_file:
      - .env
    ports:
      - ${HOST_RABBIRMQ_GUI_PORT}:15672
      - ${HOST_RABBIRMQ_PORT}:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIRMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIRMQ_PASSWORD}
      - RABBITMQ_DEFAULT_VHOST=/
    networks:
      - dev_network

networks:
  dev_network:
    driver: bridge