up:
	./run-docker.sh
exec:
	./exec-php.sh
exec-php:
	./exec-php.sh
exec-nginx:
	./exec-nginx.sh
kill:
	docker-compose kill
db:
	docker-compose exec runner.db bash
logs:
	docker-compose logs -f --tail="50"
ps:
	docker-compose ps
rm:
	docker-compose rm
